# Generated by Django 4.2.2 on 2023-09-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_alter_blogs_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='date',
        ),
        migrations.AddField(
            model_name='blogs',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='updatedat',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', null=True),
        ),
    ]
