# Generated by Django 4.2.2 on 2023-09-18 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt', null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt', null=True)),
                ('blogID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.blogs')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.myuser')),
            ],
            options={
                'verbose_name_plural': 'Users Blogs',
            },
        ),
    ]
