# Generated by Django 4.2.2 on 2023-09-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_userblogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='headerImage',
            field=models.ImageField(default=None, null=True, upload_to='upload/blogs/'),
        ),
    ]
