# Generated by Django 4.2.2 on 2023-09-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0008_comments_usercommentonblogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercommentonblogs',
            name='blogID',
        ),
        migrations.RemoveField(
            model_name='usercommentonblogs',
            name='commentID',
        ),
        migrations.RemoveField(
            model_name='usercommentonblogs',
            name='userID',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='UserCommentOnBlogs',
        ),
    ]
